function split_strategy_dir_name = SS_make_split_strategy_dir_name( ...
    split_strategy, split_metadata)
%SS_MAKE_SPLIT_STRATEGY_DIR_NAME Build a stable dataset split directory name.
switch string(split_strategy)
    case "periodic"
        split_strategy_dir_name = sprintf('periodic_%d_%d', ...
            split_metadata.train_test_ratio(1), ...
            split_metadata.train_test_ratio(2));
    case "Range_nearby"
        split_strategy_dir_name = sprintf('Range_nearby_%s_%ds_gap%ds', ...
            split_metadata.range_nearby_train_side, ...
            round(split_metadata.range_nearby_half_duration_s), ...
            round(split_metadata.range_nearby_gap_s));
    otherwise
        split_strategy_dir_name = char(regexprep(string(split_strategy), ...
            '[^A-Za-z0-9_]+', '_'));
end
end
