function SS_create_nn_h5(h5_file, source_idx, num_elements, num_freq_bins, ...
    theta_vec, freq_hz, array_depths_m, range_time_s, range_km_raw, ...
    segment_range_km, valid_sample, segment_start_time_s, ...
    segment_center_time_s, segment_stop_time_s, segment_sample_start_idx, ...
    segment_sample_stop_idx)
%SS_CREATE_NN_H5 Create one split HDF5 file and write all non-RBD metadata.
if isfile(h5_file)
    delete(h5_file);
end

num_samples = numel(source_idx);

h5create(h5_file, '/X', ...
    [num_samples, num_elements, num_freq_bins, 2], ...
    'Datatype', 'single', ...
    'ChunkSize', [1, num_elements, num_freq_bins, 2], ...
    'Deflate', 4);
h5create(h5_file, '/y_range_km', [num_samples, 1], ...
    'Datatype', 'single');
h5create(h5_file, '/valid_sample', [num_samples, 1], ...
    'Datatype', 'uint8');
h5create(h5_file, '/time/window_start_s', [num_samples, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/time/window_center_s', [num_samples, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/time/window_stop_s', [num_samples, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/time/sample_start_idx', [num_samples, 1], ...
    'Datatype', 'uint64');
h5create(h5_file, '/time/sample_stop_idx', [num_samples, 1], ...
    'Datatype', 'uint64');
h5create(h5_file, '/frequency/freq_hz', [num_freq_bins, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/array/depth_m', [num_elements, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/array/element_idx', [num_elements, 1], ...
    'Datatype', 'uint16');
h5create(h5_file, '/range/range_time_s', [numel(range_time_s), 1], ...
    'Datatype', 'double');
h5create(h5_file, '/range/range_km_raw', [numel(range_km_raw), 1], ...
    'Datatype', 'double');
h5create(h5_file, '/split/source_segment_idx', [num_samples, 1], ...
    'Datatype', 'uint64');
h5create(h5_file, '/rbd/theta_vec_rad', [numel(theta_vec), 1], ...
    'Datatype', 'double');
h5create(h5_file, '/rbd/theta_best_rad', [num_samples, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/rbd/beam_power', [num_samples, numel(theta_vec)], ...
    'Datatype', 'single', ...
    'ChunkSize', [1, numel(theta_vec)], ...
    'Deflate', 4);
h5create(h5_file, '/rbd/signal_freq_scale', [num_samples, 1], ...
    'Datatype', 'double');

h5write(h5_file, '/y_range_km', single(segment_range_km(source_idx).'));
h5write(h5_file, '/valid_sample', uint8(valid_sample(source_idx).'));
h5write(h5_file, '/time/window_start_s', segment_start_time_s(source_idx).');
h5write(h5_file, '/time/window_center_s', segment_center_time_s(source_idx).');
h5write(h5_file, '/time/window_stop_s', segment_stop_time_s(source_idx).');
h5write(h5_file, '/time/sample_start_idx', ...
    uint64(segment_sample_start_idx(source_idx).'));
h5write(h5_file, '/time/sample_stop_idx', ...
    uint64(segment_sample_stop_idx(source_idx).'));
h5write(h5_file, '/frequency/freq_hz', freq_hz(:));
h5write(h5_file, '/array/depth_m', array_depths_m(:));
h5write(h5_file, '/array/element_idx', uint16((1:num_elements).'));
h5write(h5_file, '/range/range_time_s', range_time_s(:));
h5write(h5_file, '/range/range_km_raw', range_km_raw(:));
h5write(h5_file, '/split/source_segment_idx', uint64(source_idx(:)));
h5write(h5_file, '/rbd/theta_vec_rad', theta_vec(:));
end
