% export_interferer_positions_S59_to_m.m
% Convert interferer positions in the S59 Excel file to a MATLAB script.

%% Environment setup
clear; close all; clc;

try
    tmp = matlab.desktop.editor.getActive;
    script_dir = fileparts(tmp.Filename);
catch
    script_dir = fileparts(mfilename('fullpath'));
end

function_dir = fileparts(script_dir);
scripts_dir = fileparts(function_dir);
project_dir = fileparts(scripts_dir);
origindata_dir = fullfile(project_dir, 'Origindata');

cd(script_dir);
addpath(script_dir);
addpath(genpath(function_dir));
clear tmp;

%% Input and output paths
xlsx_file = fullfile(origindata_dir, 'events', 'S59', 'Interferer_Positions.xlsx');
assert(isfile(xlsx_file) == 1, 'File not found: %s', xlsx_file);

output_file = fullfile(origindata_dir, 'events', 'S59', 'Interferer_Positions_deg.m');

%% Read and convert
position_table = readtable(xlsx_file, 'PreserveVariableNames', true);
assert(~isempty(position_table), 'Excel table is empty: %s', xlsx_file);

[lat_deg, lon_deg, lat_name, lon_name] = extractLatLonFromTable(position_table);
fprintf('Converted interferer positions: lat=%s, lon=%s, valid=%d\n', ...
    lat_name, lon_name, numel(lat_deg));

%% Write output script
fid = fopen(output_file, 'w');
assert(fid > 0, 'Cannot write file: %s', output_file);

clean_xlsx_file = strrep(xlsx_file, '\', '\\');
fprintf(fid, '%% Auto-generated by export_interferer_positions_S59_to_m.m\n');
fprintf(fid, '%% Source: %s\n\n', clean_xlsx_file);

fprintf(fid, 'lat_deg = [ ...\n');
for point_idx = 1:numel(lat_deg)
    fprintf(fid, '  %.12f;\n', lat_deg(point_idx));
end
fprintf(fid, '];\n\n');

fprintf(fid, 'lon_deg = [ ...\n');
for point_idx = 1:numel(lon_deg)
    fprintf(fid, '  %.12f;\n', lon_deg(point_idx));
end
fprintf(fid, '];\n\n');

fprintf(fid, '%% Column mapping in the source table:\n');
fprintf(fid, '%% lat column: %s\n', char(lat_name));
fprintf(fid, '%% lon column: %s\n', char(lon_name));
fclose(fid);

fprintf('Wrote: %s\n', output_file);

%% Local functions
function [lat, lon, lat_name, lon_name] = extractLatLonFromTable(position_table)
names = string(position_table.Properties.VariableNames);
lower_names = lower(names);

lat_idx = find(contains(lower_names, "lat"));
lon_idx = find(contains(lower_names, "lon") | contains(lower_names, "long"));

[lat, lat_name] = pickBestCoordColumn(position_table, names, lat_idx, ["lat", "latitude"]);
[lon, lon_name] = pickBestCoordColumn(position_table, names, lon_idx, ["lon", "longitude", "long"]);

if isempty(lat) || isempty(lon)
    error('No valid latitude/longitude columns found: %s', strjoin(names, ', '));
end

valid_idx = isfinite(lat) & isfinite(lon);
lat = lat(valid_idx);
lon = lon(valid_idx);
end

function [v, chosen_name] = pickBestCoordColumn(position_table, names, idx, preferred_tokens)
v = [];
chosen_name = "";
if isempty(idx)
    return;
end

order = idx(:).';
score = zeros(size(order));
for order_idx = 1:numel(order)
    var_name = lower(names(order(order_idx)));
    for token_idx = 1:numel(preferred_tokens)
        if contains(var_name, preferred_tokens(token_idx))
            score(order_idx) = score(order_idx) + 1;
        end
    end
end

[~, perm] = sort(score, 'descend');
order = order(perm);

for var_idx = order
    col = position_table.(names(var_idx));
    col_num = parseCoordColumn(col);
    if ~isempty(col_num) && any(isfinite(col_num))
        v = col_num(:);
        chosen_name = names(var_idx);
        return;
    end
end
end

function v = parseCoordColumn(col)
if isnumeric(col)
    v = double(col);
    return;
end

if iscell(col)
    try
        col = string(col);
    catch
        v = [];
        return;
    end
end

if isstring(col) || ischar(col)
    col = string(col);
    v = nan(numel(col), 1);
    for row_idx = 1:numel(col)
        s = strtrim(col(row_idx));
        if strlength(s) == 0
            continue;
        end

        val = parseDmsToDeg(s);
        if isfinite(val)
            v(row_idx) = val;
            continue;
        end

        match_num = regexp(char(s), '([-+]?\d+(\.\d+)?)', 'match');
        if isempty(match_num)
            continue;
        end

        val = str2double(match_num{1});
        if contains(upper(s), "W") || contains(upper(s), "S")
            val = -abs(val);
        end
        if contains(upper(s), "E") || contains(upper(s), "N")
            val = abs(val);
        end
        v(row_idx) = val;
    end
    return;
end

v = [];
end

function deg = parseDmsToDeg(s)
txt = char(strtrim(s));
txt = regexprep(txt, '^[\"'']|[\"'']$', '');
txt = strtrim(txt);

hemi = regexp(txt, '[NSEW]$', 'match', 'once', 'ignorecase');
if isempty(hemi)
    deg = nan;
    return;
end
hemi = upper(hemi);

nums = regexp(txt, '[-+]?\d+(\.\d+)?', 'match');
if isempty(nums)
    deg = nan;
    return;
end

d = str2double(nums{1});
m = 0;
s2 = 0;
if numel(nums) >= 2
    m = str2double(nums{2});
end
if numel(nums) >= 3
    s2 = str2double(nums{3});
end

deg_abs = abs(d) + m / 60 + s2 / 3600;
if hemi == 'S' || hemi == 'W'
    deg = -deg_abs;
else
    deg = deg_abs;
end
end
