function SCM_create_nn_h5(h5_file, source_idx, num_pairs, num_freq_bins, ...
    freq_hz, array_depths_m, pair_i, pair_j, range_time_s, range_km_raw, ...
    segment_range_km, valid_sample, segment_start_time_s, ...
    segment_center_time_s, segment_stop_time_s, segment_sample_start_idx, ...
    segment_sample_stop_idx)
%SCM_CREATE_NN_H5 Create one split HDF5 file for SCM pair-vector features.
if isfile(h5_file)
    delete(h5_file);
end

num_samples = numel(source_idx);
num_elements = numel(array_depths_m);
if numel(pair_i) ~= num_pairs || numel(pair_j) ~= num_pairs
    error('pair_i and pair_j must match num_pairs.');
end

h5create(h5_file, '/X', ...
    [num_samples, num_pairs, num_freq_bins, 2], ...
    'Datatype', 'single', ...
    'ChunkSize', [1, num_pairs, num_freq_bins, 2], ...
    'Deflate', 4);
h5create(h5_file, '/y_range_km', [num_samples, 1], ...
    'Datatype', 'single');
h5create(h5_file, '/valid_sample', [num_samples, 1], ...
    'Datatype', 'uint8');
h5create(h5_file, '/time/window_start_s', [num_samples, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/time/window_center_s', [num_samples, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/time/window_stop_s', [num_samples, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/time/sample_start_idx', [num_samples, 1], ...
    'Datatype', 'uint64');
h5create(h5_file, '/time/sample_stop_idx', [num_samples, 1], ...
    'Datatype', 'uint64');
h5create(h5_file, '/frequency/freq_hz', [num_freq_bins, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/array/depth_m', [num_elements, 1], ...
    'Datatype', 'double');
h5create(h5_file, '/array/element_idx', [num_elements, 1], ...
    'Datatype', 'uint16');
h5create(h5_file, '/pair/numerator_element_idx', [num_pairs, 1], ...
    'Datatype', 'uint16');
h5create(h5_file, '/pair/denominator_element_idx', [num_pairs, 1], ...
    'Datatype', 'uint16');
h5create(h5_file, '/range/range_time_s', [numel(range_time_s), 1], ...
    'Datatype', 'double');
h5create(h5_file, '/range/range_km_raw', [numel(range_km_raw), 1], ...
    'Datatype', 'double');
h5create(h5_file, '/split/source_segment_idx', [num_samples, 1], ...
    'Datatype', 'uint64');

h5write(h5_file, '/y_range_km', single(segment_range_km(source_idx).'));
h5write(h5_file, '/valid_sample', uint8(valid_sample(source_idx).'));
h5write(h5_file, '/time/window_start_s', segment_start_time_s(source_idx).');
h5write(h5_file, '/time/window_center_s', segment_center_time_s(source_idx).');
h5write(h5_file, '/time/window_stop_s', segment_stop_time_s(source_idx).');
h5write(h5_file, '/time/sample_start_idx', ...
    uint64(segment_sample_start_idx(source_idx).'));
h5write(h5_file, '/time/sample_stop_idx', ...
    uint64(segment_sample_stop_idx(source_idx).'));
h5write(h5_file, '/frequency/freq_hz', freq_hz(:));
h5write(h5_file, '/array/depth_m', array_depths_m(:));
h5write(h5_file, '/array/element_idx', uint16((1:num_elements).'));
h5write(h5_file, '/pair/numerator_element_idx', uint16(pair_i(:)));
h5write(h5_file, '/pair/denominator_element_idx', uint16(pair_j(:)));
h5write(h5_file, '/range/range_time_s', range_time_s(:));
h5write(h5_file, '/range/range_km_raw', range_km_raw(:));
h5write(h5_file, '/split/source_segment_idx', uint64(source_idx(:)));
end
